package main.java;

import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.scene.input.MouseEvent;

public interface ButtonActions
{
    void hydrogen_action(MouseEvent event);
    void lithium_action(MouseEvent event);
    void sodium_action(MouseEvent event);
    void potassium_action(MouseEvent event);
    void rubidium_action(MouseEvent event);
    void caesium_action(MouseEvent event);
    void francium_action(MouseEvent event);
    void beryllium_action(MouseEvent event);
    void magnesium_action(MouseEvent event);
    void calcium_action(MouseEvent event);
    void strontium_action(MouseEvent event);
    void barium_action(MouseEvent event);
    void radium_action(MouseEvent event);
    void scandium_action(MouseEvent event);
    void yttrium_action(MouseEvent event);
    void titanium_action(MouseEvent event);
    void zirconium_action(MouseEvent event);
    void hafnium_action(MouseEvent event);
    void rutherfordium_action(MouseEvent event);
    void lanthanum_action(MouseEvent event);
    void actinium_action(MouseEvent event);
    void vanadium_action(MouseEvent event);
    void niobium_action(MouseEvent event);
    void tantalum_action(MouseEvent event);
    void dubnium_action(MouseEvent event);
    void cerium_action(MouseEvent event);
    void thorium_action(MouseEvent event);
    void chromium_action(MouseEvent event);
    void molybdenum_action(MouseEvent event);
    void tungsten_action(MouseEvent event);
    void seaborgium_action(MouseEvent event);
    void praseodymium_action(MouseEvent event);
    void protactinium_action(MouseEvent event);
    void manganese_action(MouseEvent event);
    void technetium_action(MouseEvent event);
    void rhenium_action(MouseEvent event);
    void bohrium_action(MouseEvent event);
    void neodymium_action(MouseEvent event);
    void uranium_action(MouseEvent event);
    void iron_action(MouseEvent event);
    void ruthenium_action(MouseEvent event);
    void osmium_action(MouseEvent event);
    void hassium_action(MouseEvent event);
    void promethium_action(MouseEvent event);
    void neptunium_action(MouseEvent event);
    void cobalt_action(MouseEvent event);
    void rhodium_action(MouseEvent event);
    void iridium_action(MouseEvent event);
    void meitnerium_action(MouseEvent event);
    void samarium_action(MouseEvent event);
    void plutonium_action(MouseEvent event);
    void nickel_action(MouseEvent event);
    void palladium_action(MouseEvent event);
    void platinum_action(MouseEvent event);
    void darmstadtium_action(MouseEvent event);
    void europium_action(MouseEvent event);
    void americium_action(MouseEvent event);
    void copper_action(MouseEvent event);
    void silver_action(MouseEvent event);
    void gold_action(MouseEvent event);
    void roentgenium_action(MouseEvent event);
    void gadolinium_action(MouseEvent event);
    void curium_action(MouseEvent event);
    void zinc_action(MouseEvent event);
    void cadmium_action(MouseEvent event);
    void mercury_action(MouseEvent event);
    void copernicium_action(MouseEvent event);
    void terbium_action(MouseEvent event);
    void berkelium_action(MouseEvent event);
    void boron_action(MouseEvent event);
    void aluminium_action(MouseEvent event);
    void gallium_action(MouseEvent event);
    void indium_action(MouseEvent event);
    void thallium_action(MouseEvent event);
    void nihonium_action(MouseEvent event);
    void dysprosium_action(MouseEvent event);
    void californium_action(MouseEvent event);
    void carbon_action(MouseEvent event);
    void silicon_action(MouseEvent event);
    void germanium_action(MouseEvent event);
    void tin_action(MouseEvent event);
    void lead_action(MouseEvent event);
    void flerovium_action(MouseEvent event);
    void holmium_action(MouseEvent event);
    void einsteinium_action(MouseEvent event);
    void nitrogen_action(MouseEvent event);
    void phosphorus_action(MouseEvent event);
    void arsenic_action(MouseEvent event);
    void antimony_action(MouseEvent event);
    void bismuth_action(MouseEvent event);
    void moscovium_action(MouseEvent event);
    void erbium_action(MouseEvent event);
    void fermium_action(MouseEvent event);
    void oxygen_action(MouseEvent event);
    void sulfur_action(MouseEvent event);
    void selenium_action(MouseEvent event);
    void tellurium_action(MouseEvent event);
    void polonium_action(MouseEvent event);
    void livermorium_action(MouseEvent event);
    void thulium_action(MouseEvent event);
    void mendelevium_action(MouseEvent event);
    void fluorine_action(MouseEvent event);
    void chlorine_action(MouseEvent event);
    void bromine_action(MouseEvent event);
    void iodine_action(MouseEvent event);
    void astatine_action(MouseEvent event);
    void tennessine_action(MouseEvent event);
    void ytterbium_action(MouseEvent event);
    void nobelium_action(MouseEvent event);
    void helium_action(MouseEvent event);
    void neon_action(MouseEvent event);
    void argon_action(MouseEvent event);
    void krypton_action(MouseEvent event);
    void xenon_action(MouseEvent event);
    void radon_action(MouseEvent event);
    void oganesson_action(MouseEvent event);
    void lutetium_action(MouseEvent event);
    void lawrencium_action(MouseEvent event);

    void zoom100Action (ActionEvent event);
    void zoom150Action (ActionEvent event);
    void zoom200Action (ActionEvent event);
    void switchToListView(ActionEvent event);


}
